name: 'HostServerClient'
main: 'net.ME1312.HostServers.Load'
version: '1.8.8c'
author: ME1312
website: 'https://www.spigotmc.org/resources/hostservers.12521/'
commands:
  hostserver:
    description: All HostServer Commands
    usage: /HostServer
  host:
    description: All HostServer Commands
    usage: /Host
  'hostconfig@client':
    description: HostSever Debug Commands
    usage: '/Hostconfig@client'
permissions:
  hostserver.*:
    description: All HostServer Commands
    default: op
    children:
      hostserver.remove:
        description: Remove Player Server
        default: op