# HostServer Plugin Configuration
# This Plugin Requires SubServers and BungeeCord.
#
# Template Generation Options
Settings:
    config-version: 1.8.8c+
    GUI: true
    Server-Config:
        Max-Servers: 25
        Remove-on-close: true
        Server-dir: './HostServers'
    Port-Config:
        Max: 25569
        Min: 23123
#
# List of Templates
# Path is the directory to copy contents from
Templates:
    'My-MPS-Template':
        enabled: false
        log: true
        path: 'path/to/your/template'
        shell: './start.sh'
        stop-after: 0
        startup-commands: []
#
# End of Config